#!/usr/bin/env python3
"""
Process Malformed Posts Queue

Reads shared_malformed_report.json generated by the Bluesky Analysis Agent,
repairs the posts (fixing title/date/body issues), reposts correctly,
and deletes the old malformed posts.

Usage:
    python scripts/process_malformed_queue.py [--dry-run] [--limit N]
"""

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
from atproto import Client

# Optional Discord logging
try:
    from discord_logger import log_post_success, log_error
    DISCORD_LOGGING = True
except ImportError:
    DISCORD_LOGGING = False


# Bot credentials mapping
BOT_CREDENTIALS = {
    'roundupnewsbotsa.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_SA',
        'password_env': 'BLUESKY_PASSWORD_SA',
        'state': 'SA'
    },
    'roundupnewsbotnsw.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_NSW',
        'password_env': 'BLUESKY_PASSWORD_NSW',
        'state': 'NSW'
    },
    'roundupnewsbotqld.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_QLD',
        'password_env': 'BLUESKY_PASSWORD_QLD',
        'state': 'QLD'
    },
    'roundupnewsbotvic.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_VIC',
        'password_env': 'BLUESKY_PASSWORD_VIC',
        'state': 'VIC'
    },
    'roundupnewsbotwa.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_WA',
        'password_env': 'BLUESKY_PASSWORD_WA',
        'state': 'WA'
    },
    'roundupnewsbottas.bsky.social': {
        'handle_env': 'BLUESKY_HANDLE_TAS',
        'password_env': 'BLUESKY_PASSWORD_TAS',
        'state': 'TAS'
    },
}


def extract_clean_title(text: str) -> str:
    """
    Extract just the title from a malformed post text.
    
    The malformed posts have format:
    "Title + Body snippet...\nDate\nCouncil\n#Hashtags"
    
    We need to extract just the title.
    """
    if not text:
        return ""
    
    # Split on first newline - title is before it
    lines = text.split('\n')
    first_line = lines[0].strip()
    
    # The title often gets merged with the body/excerpt
    # Look for patterns where the body starts
    
    # Pattern 1: Date at the end of first line "Title 03 December 2025 Body..."
    date_pattern = r'\s+\d{1,2}\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{4}\s+'
    match = re.search(date_pattern, first_line, re.IGNORECASE)
    if match:
        # Title is before the date
        title = first_line[:match.start()].strip()
        return title
    
    # Pattern 2: "Published on XX Month YYYY" embedded
    published_pattern = r'Published on \d{1,2} \w+ \d{4}'
    match = re.search(published_pattern, first_line, re.IGNORECASE)
    if match:
        title = first_line[:match.start()].strip()
        return title
    
    # Pattern 3: Repeated sentence start (title + first sentence of body)
    # e.g., "King tides expected from Friday Townsville City Council is encouraging..."
    # Split at common sentence starters after title
    body_starters = [
        r'(?<=[a-z])\s+(?:The|A|An|Council|City|Shire|Mayor|Residents|Locals|More than|As|Pet|Getting|At|On|Over|In|Following|The City|City of)\s+[A-Z]',
    ]
    for pattern in body_starters:
        match = re.search(pattern, first_line)
        if match:
            title = first_line[:match.start() + 1].strip()  # +1 to include the lowercase letter
            return title
    
    # Pattern 4: Title ends with recognizable council phrase
    # Look for repeated content pattern
    # Many posts have "Title Body preview..." where title might end with key noun
    
    # Fallback: If first line is very long (>100 chars), try to find a logical break
    if len(first_line) > 100:
        # Look for sentence ending followed by capital letter start
        sentence_break = re.search(r'[.!?]\s+[A-Z]', first_line)
        if sentence_break:
            # Assume title is the first sentence
            potential_title = first_line[:sentence_break.start() + 1]
            if len(potential_title) < 150:
                return potential_title
        
        # Try ellipsis truncation point
        if '...' in first_line:
            # The ... is usually where content was truncated
            # Title is probably the first part before significant body text
            pass
    
    # Last resort: truncate at reasonable length
    if len(first_line) > 120:
        # Find last space before 120 chars
        truncate_at = first_line[:120].rfind(' ')
        if truncate_at > 0:
            return first_line[:truncate_at]
    
    return first_line


def extract_council_name(text: str) -> str:
    """Extract council name from post text."""
    lines = text.split('\n')
    # Council name is typically the 3rd or 4th line (after Title, Date)
    for line in lines[1:4]:
        line = line.strip()
        # Skip if it's a date or hashtags
        if line.startswith('#') or not line:
            continue
        if re.match(r'\d{1,2}\s+\w+\s+\d{4}', line):
            continue
        # Likely the council name
        if 'Council' in line or 'Shire' in line or 'City of' in line:
            return line
    return ""


def delete_post(client: Client, uri: str) -> bool:
    """Delete a post by URI."""
    try:
        # Extract rkey from URI
        # Format: at://did:plc:xxx/app.bsky.feed.post/rkey
        parts = uri.split('/')
        rkey = parts[-1]
        
        client.delete_post(rkey)
        return True
    except Exception as e:
        print(f"  ❌ Failed to delete post: {e}")
        return False


def delete_bookmark(client: Client, post_uri: str) -> bool:
    """Delete bookmark for a post (cleanup)."""
    try:
        # Get bookmarks and find the one matching this post
        bookmarks = client.app.bsky.notification.list_notifications()
        # Note: Bookmark API is undocumented, may need adjustment
        return True
    except Exception as e:
        # Bookmarks are optional cleanup, don't fail on error
        return False


def process_queue(report_path: str, dry_run: bool = False, limit: int = 0):
    """Process all malformed posts in the report."""
    load_dotenv()
    
    # Load report
    with open(report_path) as f:
        items = json.load(f)
    
    if not items:
        print("No malformed posts to process")
        return
    
    print(f"Found {len(items)} malformed posts to process")
    
    if limit > 0:
        items = items[:limit]
        print(f"Limiting to {limit} items")
    
    # Group by handle (bot account)
    by_handle = {}
    for item in items:
        handle = item['handle']
        if handle not in by_handle:
            by_handle[handle] = []
        by_handle[handle].append(item)
    
    # Track results
    processed = 0
    deleted = 0
    failed = 0
    
    # Process each bot's posts
    for handle, posts in by_handle.items():
        print(f"\n{'='*60}")
        print(f"Processing {len(posts)} posts for {handle}")
        print(f"{'='*60}")
        
        # Get credentials
        creds = BOT_CREDENTIALS.get(handle)
        if not creds:
            print(f"  ⚠️ Unknown handle: {handle}, skipping")
            failed += len(posts)
            continue
        
        bot_handle = os.environ.get(creds['handle_env'])
        bot_password = os.environ.get(creds['password_env'])
        
        if not bot_handle or not bot_password:
            print(f"  ⚠️ Missing credentials for {handle}, skipping")
            failed += len(posts)
            continue
        
        # Authenticate
        if not dry_run:
            try:
                client = Client()
                client.login(bot_handle, bot_password)
                print(f"  ✓ Authenticated as {bot_handle}")
            except Exception as e:
                print(f"  ❌ Auth failed: {e}")
                failed += len(posts)
                continue
        
        # Process each post
        for item in posts:
            uri = item['uri']
            original_text = item['text']
            external_url = item['external_url']
            
            # Extract clean title
            clean_title = extract_clean_title(original_text)
            council_name = extract_council_name(original_text)
            
            print(f"\n  📰 Original: {original_text[:60]}...")
            print(f"  🔧 Clean title: {clean_title}")
            print(f"  🏛️ Council: {council_name}")
            print(f"  🔗 URL: {external_url[:60]}...")
            
            if dry_run:
                print(f"  [DRY RUN] Would delete: {uri}")
                print(f"  [DRY RUN] Would NOT repost (scraper should fix at source)")
                processed += 1
                continue
            
            # DELETE the old malformed post
            # We do NOT repost here - the scraper should re-scrape and post correctly
            # with the safety valve in place
            try:
                if delete_post(client, uri):
                    print(f"  ✓ Deleted malformed post")
                    deleted += 1
                    processed += 1
                else:
                    failed += 1
            except Exception as e:
                print(f"  ❌ Error: {e}")
                failed += 1
            
            # Rate limit
            time.sleep(0.5)
    
    # Summary
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"Processed: {processed}")
    print(f"Deleted: {deleted}")
    print(f"Failed: {failed}")
    
    if not dry_run and deleted > 0:
        # Clear the processed items from the report
        remaining = [item for item in items if item not in items[:processed]]
        with open(report_path, 'w') as f:
            json.dump(remaining, f, indent=2)
        print(f"\nUpdated report: {len(remaining)} items remaining")


def main():
    parser = argparse.ArgumentParser(description='Process malformed posts queue')
    parser.add_argument('--dry-run', action='store_true', 
                        help='Show what would be done without making changes')
    parser.add_argument('--limit', type=int, default=0,
                        help='Limit number of posts to process')
    parser.add_argument('--report', type=str, 
                        default='shared_malformed_report.json',
                        help='Path to malformed report JSON')
    
    args = parser.parse_args()
    
    # Find report file
    report_path = Path(args.report)
    if not report_path.is_absolute():
        # Check relative to project root
        project_root = Path(__file__).parent.parent
        report_path = project_root / args.report
    
    if not report_path.exists():
        print(f"Report file not found: {report_path}")
        sys.exit(1)
    
    process_queue(str(report_path), dry_run=args.dry_run, limit=args.limit)


if __name__ == '__main__':
    main()
